config/routes.rb
Rails.application.routes.draw do
  resources :especies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/especie.rb
class Especie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/especies_controller.rb
class EspeciesController < ApplicationController
  before_action :set_especy, only: [:show, :edit, :update, :destroy]

  # GET /especies
  # GET /especies.json
  def index
    @especies = Especie.all
  end

  # GET /especies/1
  # GET /especies/1.json
  def show
  end

  # GET /especies/new
  def new
    @especy = Especie.new
  end

  # GET /especies/1/edit
  def edit
  end

  # POST /especies
  # POST /especies.json
  def create
    @especy = Especie.new(especy_params)

    respond_to do |format|
      if @especy.save
        format.html { redirect_to @especy, notice: 'Especie was successfully created.' }
        format.json { render :show, status: :created, location: @especy }
      else
        format.html { render :new }
        format.json { render json: @especy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /especies/1
  # PATCH/PUT /especies/1.json
  def update
    respond_to do |format|
      if @especy.update(especy_params)
        format.html { redirect_to @especy, notice: 'Especie was successfully updated.' }
        format.json { render :show, status: :ok, location: @especy }
      else
        format.html { render :edit }
        format.json { render json: @especy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /especies/1
  # DELETE /especies/1.json
  def destroy
    @especy.destroy
    respond_to do |format|
      format.html { redirect_to especies_url, notice: 'Especie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_especy
      @especy = Especie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def especy_params
      params.require(:especy).permit(:nome, :cientifico, :nome, :popular)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/especies_helper.rb
module EspeciesHelper
end

app/views/especies/_form.html.erb
<%= form_with(model: especy, local: true) do |form| %>
  <% if especy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(especy.errors.count, "error") %> prohibited this especy from being saved:</h2>

      <ul>
      <% especy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cientifico %>
    <%= form.text_field :cientifico %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :popular %>
    <%= form.text_field :popular %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/especies/edit.html.erb
<h1>Editing Especy</h1>

<%= render 'form', especy: @especy %>

<%= link_to 'Show', @especy %> |
<%= link_to 'Back', especies_path %>

app/views/especies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Especies</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cientifico</th>
      <th>Nome</th>
      <th>Popular</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @especies.each do |especy| %>
      <tr>
        <td><%= especy.nome %></td>
        <td><%= especy.cientifico %></td>
        <td><%= especy.nome %></td>
        <td><%= especy.popular %></td>
        <td><%= link_to 'Show', especy %></td>
        <td><%= link_to 'Edit', edit_especy_path(especy) %></td>
        <td><%= link_to 'Destroy', especy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Especy', new_especy_path %>

app/views/especies/new.html.erb
<h1>New Especy</h1>

<%= render 'form', especy: @especy %>

<%= link_to 'Back', especies_path %>

app/views/especies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @especy.nome %>
</p>

<p>
  <strong>Cientifico:</strong>
  <%= @especy.cientifico %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @especy.nome %>
</p>

<p>
  <strong>Popular:</strong>
  <%= @especy.popular %>
</p>

<%= link_to 'Edit', edit_especy_path(@especy) %> |
<%= link_to 'Back', especies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>